Repository Binlandorg/binland-website-client, pull requests merged in 2024-05, with the labels that each got.

#149 fix: social media and focus in footer links
  src/components/Footer/Footer.styles.ts
  src/components/Hero/socialMediaBar/SocialMediaBar.styles.ts
  src/components/Hero/socialMediaBar/SocialMediaBar.tsx
  src/components/SocialMedia/SocialMedia.styles.ts
  src/components/SocialMedia/SocialMedia.tsx
  src/types/ui/Link.ts
Labels: bug, enhancement

#153 fix(header): Styling corrected
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/ui/Select/Select.styles.ts
  src/ui/Select/Select.tsx
Labels: fix

#155 task: added Twitch button network
  src/components/ContactUs/ContactUsInformation/ContactUsInformation.tsx
  src/components/Hero/Hero.styles.ts
  src/components/Hero/socialMediaBar/SocialMediaBar.styles.ts
  src/components/Hero/socialMediaBar/SocialMediaBar.tsx
  src/components/SocialMedia/SocialMedia.tsx
Labels: enhancement
